Added logic to create a month rolling release

diff --git a/.github/workflows/run_every_hour.yml b/.github/workflows/run_every_hour.yml
--- a/.github/workflows/run_every_hour.yml
+++ b/.github/workflows/run_every_hour.yml
@@ -26,7 +26,7 @@ env:
   dotnet-configuration: Release
   DOTNET_NOLOGO: true
   PROGRAM_NAME: WowAHaha
-  LATEST_CSV_TAG: latest_csv
+  #LATEST_CSV_TAG: latest_csv
   RELEASE_CSV_PREFIX: wow_ah_csv_
   FORCE_RELEASE: false # set to true to force a release (useful for testing)
   SKIP_PREVIOUS_RELEASE_DOWNLOAD: false
@@ -51,6 +51,76 @@ jobs:
       packages: write
       contents: write
     steps:
+      - name: Prepare
+        id: prepare
+        shell: python
+        run: |
+          import os
+          import datetime
+          import json
+
+          true_values = {'true', '1', 'yes', 'on', 'y', 'enable', 'enabled', '#t', '#true', 'ok', 'okay'}
+          now = datetime.datetime.utcnow()
+
+          year_and_month = now.strftime('%Y_%m')
+          release_csv_suffix = year_and_month + (os.getenv('RELEASE_CSV_SUFFIX') or '.7z')
+
+          with open(os.getenv('GITHUB_STEP_SUMMARY'), 'a') as step_summary:
+            step_summary.write(f'# Run the WowAHaha project for *{year_and_month}* \n')
+
+            with open(os.getenv('GITHUB_ENV'), 'a') as env_file:
+              env_file.write(f'RELEASE_CSV_SUFFIX={release_csv_suffix}\n')
+              env_file.write(f'RELEASE_YEAR_AND_MONTH={year_and_month}\n')
+          
+              allowed_actors = r"""${{ secrets.ALLOWED_ACTOR || vars.ALLOWED_ACTOR || env.ALLOWED_ACTOR || github.repository_owner }}""".strip()
+
+              github_actor = r"""${{ github.actor }}""".strip()
+              overwritten = 0
+              if allowed_actors:
+                if ',' in allowed_actors:
+                  allowed_actors = [s.strip() for s in allowed_actors.split(',')]
+                  if github_actor in allowed_actors:
+                    env_file.write(f'''ALLOWED_ACTOR={github_actor}\n''')
+                else:
+                  env_file.write(f'''ALLOWED_ACTOR={allowed_actors}\n''')
+          
+              if allowed_actors and github_actor in allowed_actors:
+                step_summary.write(f":white_check_mark: Actor {github_actor} is allowed.\n")
+              else:
+                step_summary.write(f":x: Actor {github_actor} is not allowed.\n")
+
+              for bool_env_var in ['FAST_RELEASE', 'USE_WORKING_DIR_CACHE', 'SKIP_PREVIOUS_RELEASE_DOWNLOAD', 'SKIP_BUILD_ATTEST', 'FIRST_RUN', 'FORCE_RELEASE']:
+                if os.getenv(bool_env_var, '').lower() in true_values:
+                  env_file.write(f'{bool_env_var}=true\n')
+                else:
+                  env_file.write(f'{bool_env_var}=false\n')
+  
+              step_summary.write('## :gear: Environment variables \n')
+
+              
+              if os.getenv('FAST_RELEASE', '') == 'true':
+                env_file.write('USE_WORKING_DIR_CACHE=false\n')
+                env_file.write('SKIP_BUILD_ATTEST=true\n')
+                overwriten += 2
+          
+              if now.day == 1:
+                env_file.write('FIRST_DAY_OF_MONTH=true\n')
+                overwritten += 1
+          
+              if not os.getenv('LATEST_CSV_TAG', ''):
+                env_file.write(f'LATEST_CSV_TAG=csv_{year_and_month}\n')
+                overwritten += 1
+              
+              if overwritten > 0:
+                step_summary.write(f'### Some environment variables were dynamically added/overwritten: {overwritten} \n')
+  
+              step_summary.write('| Variable | Value |\n')
+              step_summary.write('|----------|------------------|\n')
+              for env_var in (['FAST_RELEASE', 'USE_WORKING_DIR_CACHE', 'SKIP_PREVIOUS_RELEASE_DOWNLOAD', 'SKIP_BUILD_ATTEST', 'FIRST_RUN', 'FORCE_RELEASE'] +
+                              ['LATEST_CSV_TAG', 'RELEASE_CSV_PREFIX', 'FIRST_DAY_OF_MONTH']):
+                value = os.getenv(env_var, '(not set)')
+                step_summary.write(f"| {env_var} | {value} |\n")
+          
       - uses: actions/checkout@v4.2.2
         with:
           submodules: 'recursive'
@@ -70,28 +140,39 @@ jobs:
       - name: Build
         run: |
           dotnet build --configuration ${{ env.dotnet-configuration }} --no-restore
+          
+          
+      - uses: mukunku/tag-exists-action@v1.6.0
+        id: check-tag
+        with:
+          tag: ${{ env.LATEST_CSV_TAG }}
 
-
+      - name: Skip previous release download
+        if: steps.check-tag.outputs.exists != 'true'
+        run: |
+          echo "SKIP_PREVIOUS_RELEASE_DOWNLOAD=true" >> $GITHUB_ENV
+          echo "## :information_source: Skipping previous release download as tag `${{ env.LATEST_CSV_TAG }}` does not exist." >> $GITHUB_STEP_SUMMARY
+      
+      
       - name: Download latest files from Release
         uses: robinraju/release-downloader@v1
         id: download_release
         if: env.SKIP_PREVIOUS_RELEASE_DOWNLOAD != 'true'
         with:
           tag: ${{ env.LATEST_CSV_TAG }}
-          fileName: '${{ env.RELEASE_CSV_PREFIX }}*.7z'
+          fileName: '${{ env.RELEASE_CSV_PREFIX }}*${{ env.RELEASE_CSV_SUFFIX }}'
           extract: false
-
 
       - name: Cache wd directory
         uses: actions/cache@v3
         id: wd_cache
-        if: env.FAST_RELEASE != 'true' && env.USE_WORKING_DIR_CACHE == 'true'
+        if: env.USE_WORKING_DIR_CACHE == 'true'
         with:
           path: wd
           enableCrossOsArchive: true
-          key: ${{ env.PROGRAM_NAME }}-csv-wd-${{ hashFiles('**/*.7z') }}-${{ hashFiles('**/*.csproj') }}
+          key: ${{ env.PROGRAM_NAME }}-csv-wd-${{ env.RELEASE_CSV_SUFFIX }}-${{ hashFiles('**/*.7z') }}-${{ hashFiles('**/*.csproj') }}
           restore-keys: |
-            ${{ env.PROGRAM_NAME }}-csv-wd-
+            ${{ env.PROGRAM_NAME }}-csv-wd-${{ env.RELEASE_CSV_SUFFIX }}-
 
       - name: Unzip latest files
         if: env.SKIP_PREVIOUS_RELEASE_DOWNLOAD != 'true'
@@ -106,7 +187,10 @@ jobs:
               rm -rf wd/*.zip
               rm -rf wd/wd
               echo ":package: Extracted files from $downloaded_file" >> $GITHUB_STEP_SUMMARY
-              echo "PREVIOUS_RELEASE_DOWNLOADED_FILE=$downloaded_file" >> $GITHUB_ENV
+              # create a physical hard link to the previous release archive
+              PREVIOUS_RELEASE_DOWNLOADED_FILE="${{ env.RELEASE_CSV_PREFIX }}previous_release${{ env.RELEASE_CSV_SUFFIX }}"
+              ln "$downloaded_file" $PREVIOUS_RELEASE_DOWNLOADED_FILE
+              echo "PREVIOUS_RELEASE_DOWNLOADED_FILE=$PREVIOUS_RELEASE_DOWNLOADED_FILE" >> $GITHUB_ENV
               echo "PREVIOUS_RELEASE_DOWNLOADED_FILE_SOURCE=release" >> $GITHUB_ENV
             else
               echo "No downloaded files found. Aborting." 1>&2
@@ -114,7 +198,7 @@ jobs:
             fi
           else
             echo ":information_source: Using cached data instead of downloading from release." >> $GITHUB_STEP_SUMMARY
-            file_name=${{ env.RELEASE_CSV_PREFIX }}cached.7z
+            file_name=${{ env.RELEASE_CSV_PREFIX }}cached${{ env.RELEASE_CSV_SUFFIX }}
             pushd wd
             rm -rf *.7z
             rm -rf *.zip
@@ -194,7 +278,7 @@ jobs:
                   step_summary.write(f"| {file.relative_to(wd)} | {hash} | {human_readable_size(size)} |\n")
 
       - name: Run WowAHaha
-        if: (vars.ALLOWED_ACTOR || github.repository_owner) == github.actor || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
+        if: env.ALLOWED_ACTOR == github.actor || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
         timeout-minutes: 10
         id: run
         run: |
@@ -258,7 +342,7 @@ jobs:
       - name: Create a 7z file of csv files
         id: csv_7z
         run: |
-          file_name="${{ env.RELEASE_CSV_PREFIX }}$(date +'%Y_%m_%d_%H_%M_%S').7z"
+          file_name="${{ env.RELEASE_CSV_PREFIX }}${{ env.RELEASE_CSV_SUFFIX }}"
           pushd wd
           7z a ${{ env.SEVENZIP_FLAGS }} "../$file_name" *
           popd
@@ -294,11 +378,11 @@ jobs:
             echo "| :page_facing_up: New Size | $(ls -lh "$file_name" | awk '{print $5}') |" >> $GITHUB_STEP_SUMMARY
             echo "| :chart_with_upwards_trend: Delta Size | $delta_size KiB (${delta_percent}%) |" >> $GITHUB_STEP_SUMMARY
 
-            #if python -c "import math; print(math.log1p($size) - math.log1p($old_size) < -0.1)" | grep -q "True"; then
-            #  echo "The resulting 7z file is smaller than the previous one. This is a regression. Aborting." 1>&2
-            #  echo "### :warning: The resulting 7z file is smaller than the previous one. This is a regression. Aborting." >> $GITHUB_STEP_SUMMARY
-            #  exit 2
-            #fi
+            if python -c "import math; print(math.log1p($size) - math.log1p($old_size) < -0.1)" | grep -q "True"; then
+              echo "The resulting 7z file is smaller than the previous one. This is a regression. Aborting." 1>&2
+              echo "### :warning: The resulting 7z file is smaller than the previous one. This is a regression. Aborting." >> $GITHUB_STEP_SUMMARY
+              exit 2
+            fi
           
             if python -c "print(float($delta_percent) == 0)" | grep -q "True"; then
               echo ARCHIVE_NO_CHANGE=true >> $GITHUB_ENV
@@ -307,7 +391,7 @@ jobs:
           else
             echo "## :warning: No previous file to compare to." >> $GITHUB_STEP_SUMMARY
             echo "No previous file to compare to. Skipping size comparison." 1>&2
-            if [ "${{ env.FIRST_RUN }}" != "true" ]; then
+            if [ "${{ env.FIRST_DAY_OF_MONTH || env.FIRST_RUN }}" != "true" ]; then
               echo "## :warning: If it's the first run, you must set `FIRST_RUN` to `true` for the script to work." >> $GITHUB_STEP_SUMMARY
               exit 5
             fi
@@ -315,7 +399,7 @@ jobs:
 
 
       - name: Attest Build Provenance of csv files
-        if: env.FAST_RELEASE != 'true' && env.SKIP_BUILD_ATTESTATION != 'true' && env.ARCHIVE_NO_CHANGE != 'true' && github.event_name != 'schedule' # disable on schedule to speed up
+        if: env.SKIP_BUILD_ATTESTATION != 'true' && env.ARCHIVE_NO_CHANGE != 'true' && github.event_name != 'schedule' # disable on schedule to speed up
         uses: actions/attest-build-provenance@v1
         with:
           subject-path: 'wd/*'
@@ -327,7 +411,7 @@ jobs:
           subject-path: "${{ steps.csv_7z.outputs.sevenzip_file_name }}"
 
       - uses: rickstaa/action-create-tag@v1
-        if: env.ARCHIVE_NO_CHANGE != 'true' && (vars.ALLOWED_ACTOR || github.repository_owner) == github.actor && (env.FORCE_RELEASE == 'true' || (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'))
+        if: env.ARCHIVE_NO_CHANGE != 'true' && env.ALLOWED_ACTOR == github.actor && (env.FORCE_RELEASE == 'true' || (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'))
         id: "tag_create"
         with:
           tag: ${{ env.LATEST_CSV_TAG }}
@@ -336,12 +420,12 @@ jobs:
 
       - name: Create a new release
         uses: ncipollo/release-action@v1
-        if: env.ARCHIVE_NO_CHANGE != 'true' && (vars.ALLOWED_ACTOR || github.repository_owner) == github.actor && (env.FORCE_RELEASE == 'true' || (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'))
+        if: env.ARCHIVE_NO_CHANGE != 'true' && env.ALLOWED_ACTOR == github.actor && (env.FORCE_RELEASE == 'true' || (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'))
         with:
           allowUpdates: true
           artifactErrorsFailBuild: true
           artifacts: "${{ steps.csv_7z.outputs.sevenzip_file_name }}"
-          name: Latest csv files
+          name: Latest csv files ${{ env.RELEASE_YEAR_AND_MONTH }}
           body: |
             This is an automated release of the latest csv files.
             From ${{ github.actor }} (${{ github.event_name }}) @ ${{ github.sha }}
@@ -349,5 +433,5 @@ jobs:
           prerelease: false
           makeLatest: true
           replacesArtifacts: true
-          removeArtifacts: true
+          removeArtifacts: false
           tag: ${{ env.LATEST_CSV_TAG }}
